---
- name: Add a User
  hosts: all
  become: true
  vars_prompt:
    - name: new_username
      prompt: "Enter the username of the new user:"
      private: no
    - name: new_password
      prompt: "Enter the password for the new user:"
      private: yes
  tasks:
    - name: Add the new user
      user:
        name: "{{ new_username }}"
        password: "{{ new_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes
