---
- name: Essential Tools and Public IP
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential tools
      apt:
        name:
          - curl
          - vim
          - htop
        state: present
