# Playbook: update_droplet.yml
# Description: This Ansible playbook updates the APT cache.
# Author: Berger
# Date: 2023-07-27

- name: Update and install Docker on Droplet
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
