---
- name: Update APT packages
  hosts: all
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true

    - name: Upgrade all APT packages
      apt:
        upgrade: dist
        autoremove: true
